name: circuitbox
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  json_serializable: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/icon.png"

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - lib/assets/icons/logo.png
    - lib/assets/icons/icon.png
    - lib/helvetica/

  fonts:
    - family: Helvetica
      fonts:
        - asset: lib/helvetica/HelveticaNeueBold.otf
        - asset: lib/helvetica/HelveticaNeueLight.otf
        - asset: lib/helvetica/HelveticaNeueRoman.otf
        - asset: lib/helvetica/HelveticaNeueUltraLight.otf
